# -*- coding: utf-8 -*-
"""example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16uOcaqJod6DqD-wznbtYc5Lejs9qOU8i
"""

def prob_for_famous(n):
  y = max(n)
  x = sum(n)
  
  a = y / x
  return a

 
  
b = [12,23,34,123,45,345,4566,654654,4]
print (prob(b))

c = [12,23,34,45,1,2,3,4,55555,67]
print (prob_for_famous(c))

