# -*- coding: utf-8 -*-
"""hypothesis_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geBWJsrG8u5RojLVPUdPzEZ4g_0sVJiY
"""

def prob(m,a):
  try:
    if m<len(a):
      print("You have qualified the conditions. The answer that you are seeking is:")
      b = a[0:m+1]
      print (b)
    else:
      
      if m == len(a):
        print ("You are not putting the right option. The value has to be less than the value of the length of the original list.")
      if m > len(a):
        print ("You have put an invalid option. The value has to be less than the value of the length of the original list.")
    y = max(b)
    x = sum(b)
    b.sort()
    length = len(b)
    second_largest = b[length-2]
    third_largest = b[length-3]
      
    a = y/x
    print ("The probability of attaching to the most famous point is,", a)
    if a<0.45:
      print("The probability is too less to rely on that data point, so we choose the second largest data point.")
      c = second_largest/x
      print ("The probability of attaching to the second most famous point is,", c)
      if c<0.45:
             print("The probability is too less to rely on that data point, so we choose the third largest data point.")
             dc = third_largest/x
             print ("The probability of attaching to the third most famous point is,", dc)

             
      
  except:
      print ("There can be some problem in the new section of the code. Please check them.")

    
parameter_1 = int(input("Please enter a subset from the inital list:"))
parameter_2 = [21,23,123,3,34,34,34455555,56]
result_1 = prob(parameter_1,parameter_2)
print(result_1)