# -*- coding: utf-8 -*-
"""probability for attachment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16uOcaqJod6DqD-wznbtYc5Lejs9qOU8i
"""

def prob_for_famous(n):
  u = sorted((n),reverse=True)[:3]
  print ("The maximum values in our list are:", u)
  y = max(u)
  x = sum(n)
  
  a = y / x
  return "The probability of attaching to the most famous point is,",a



















