# -*- coding: utf-8 -*-
"""probability for attachment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16uOcaqJod6DqD-wznbtYc5Lejs9qOU8i
"""

def prob_for_famous(n):
  u = sorted((n),reverse=True)[:3]
  print ("The maximum values in our list are:", u)
  y = max(u)
  x = sum(n)
  
  a = y / x
  return "The probability of attaching to the most famous point is,",a

#making a function for choosing between ARIMA, ANN and HYBRID MODEL
#we will choose a model whose R(squared) value is highest
def choose(rsqurd):
  for i in rsqurd:
    p = max(rsqurd)
  return p













e





